export const mockUser = {
	id: 'user_1',
	name: 'John Doe',
	email: 'demo@devstash.io',
	image: null,
	isPro: true,
};

export const mockItemTypes = [
	{ id: 'type_snippet', name: 'Snippet', icon: 'Code', color: '#3b82f6', category: 'TEXT', isSystem: true },
	{ id: 'type_prompt', name: 'Prompt', icon: 'Sparkles', color: '#8b5cf6', category: 'TEXT', isSystem: true },
	{ id: 'type_command', name: 'Command', icon: 'Terminal', color: '#f97316', category: 'TEXT', isSystem: true },
	{ id: 'type_note', name: 'Note', icon: 'StickyNote', color: '#fde047', category: 'TEXT', isSystem: true },
	{ id: 'type_link', name: 'Link', icon: 'Link', color: '#10b981', category: 'URL', isSystem: true },
	{ id: 'type_file', name: 'File', icon: 'File', color: '#6b7280', category: 'FILE', isSystem: true },
	{ id: 'type_image', name: 'Image', icon: 'Image', color: '#ec4899', category: 'FILE', isSystem: true },
];

export const mockCollections = [
	{
		id: 'col_1',
		name: 'React Patterns',
		description: 'Common React patterns and hooks',
		isFavorite: true,
		itemCount: 12,
		dominantTypeId: 'type_snippet',
	},
	{
		id: 'col_2',
		name: 'Python Snippets',
		description: 'Useful Python code snippets',
		isFavorite: false,
		itemCount: 8,
		dominantTypeId: 'type_snippet',
	},
	{
		id: 'col_3',
		name: 'Context Files',
		description: 'AI context files for projects',
		isFavorite: true,
		itemCount: 5,
		dominantTypeId: 'type_file',
	},
	{
		id: 'col_4',
		name: 'Interview Prep',
		description: 'Technical interview preparation',
		isFavorite: false,
		itemCount: 24,
		dominantTypeId: 'type_note',
	},
	{
		id: 'col_5',
		name: 'Git Commands',
		description: 'Frequently used git commands',
		isFavorite: true,
		itemCount: 15,
		dominantTypeId: 'type_command',
	},
	{
		id: 'col_6',
		name: 'AI Prompts',
		description: 'Curated AI prompts for coding',
		isFavorite: false,
		itemCount: 18,
		dominantTypeId: 'type_prompt',
	},
];

export const mockItems = [
	{
		id: 'item_1',
		title: 'useAuth Hook',
		description: 'Custom authentication hook for React applications',
		content: `import { useSession } from "next-auth/react";\n\nexport function useAuth() {\n  const { data: session, status } = useSession();\n  return { user: session?.user, isLoading: status === "loading" };\n}`,
		language: 'typescript',
		isFavorite: true,
		isPinned: true,
		itemTypeId: 'type_snippet',
		tags: ['react', 'auth', 'hooks'],
		collectionIds: ['col_1'],
		createdAt: '2026-01-15T10:00:00Z',
	},
	{
		id: 'item_2',
		title: 'API Error Handling Pattern',
		description: 'Fetch wrapper with exponential backoff retry logic',
		content: `async function fetchWithRetry(url: string, retries = 3) {\n  for (let i = 0; i < retries; i++) {\n    try {\n      return await fetch(url);\n    } catch (e) {\n      if (i === retries - 1) throw e;\n      await new Promise(r => setTimeout(r, 2 ** i * 1000));\n    }\n  }\n}`,
		language: 'typescript',
		isFavorite: false,
		isPinned: true,
		itemTypeId: 'type_snippet',
		tags: ['api', 'error-handling', 'typescript'],
		collectionIds: ['col_1', 'col_4'],
		createdAt: '2026-01-15T11:00:00Z',
	},
	{
		id: 'item_3',
		title: 'Code Review Prompt',
		description: 'Prompt for thorough code reviews',
		content: 'Review the following code for: 1) Security vulnerabilities 2) Performance issues 3) Code clarity 4) Edge cases. Be concise and actionable.',
		language: null,
		isFavorite: false,
		isPinned: false,
		itemTypeId: 'type_prompt',
		tags: ['code-review', 'ai'],
		collectionIds: ['col_6'],
		createdAt: '2026-01-16T09:00:00Z',
	},
	{
		id: 'item_4',
		title: 'Git Undo Last Commit',
		description: 'Keep changes staged after undoing commit',
		content: 'git reset --soft HEAD~1',
		language: 'bash',
		isFavorite: false,
		isPinned: false,
		itemTypeId: 'type_command',
		tags: ['git', 'undo'],
		collectionIds: ['col_5'],
		createdAt: '2026-01-17T14:00:00Z',
	},
	{
		id: 'item_5',
		title: 'Tailwind CSS Cheatsheet',
		description: 'Quick reference for Tailwind v4 utility classes',
		content:
			'# Tailwind v4 Quick Reference\n\n## Flexbox\n- `flex`, `flex-col`, `items-center`, `justify-between`\n\n## Grid\n- `grid`, `grid-cols-3`, `gap-4`',
		language: null,
		isFavorite: true,
		isPinned: false,
		itemTypeId: 'type_note',
		tags: ['tailwind', 'css', 'reference'],
		collectionIds: ['col_4'],
		createdAt: '2026-01-18T08:00:00Z',
	},
	{
		id: 'item_6',
		title: 'shadcn/ui Docs',
		description: 'Component library built on Radix UI',
		content: null,
		url: 'https://ui.shadcn.com',
		language: null,
		isFavorite: false,
		isPinned: false,
		itemTypeId: 'type_link',
		tags: ['ui', 'components'],
		collectionIds: ['col_1'],
		createdAt: '2026-01-19T10:00:00Z',
	},
];

export const mockItemTypeCounts: Record<string, number> = {
	type_snippet: 24,
	type_prompt: 18,
	type_command: 15,
	type_note: 12,
	type_file: 5,
	type_image: 3,
	type_link: 8,
};
